baseURL = 'https://www.stuffs.dev/'
languageCode = 'en'
title = 'Stuffs.dev'
theme = "hugo-theme-monochrome"
canonifyURLs = true

[params]
footer = 'Copyright © 2022 by Michal Pasierbski'

[markup.goldmark.renderer]
unsafe= true
