baseURL = 'https://www.stuffs.dev/'
defaultContentLanguage = 'en'
title = 'Stuffs.dev'
theme = "papermod"
canonifyURLs = true
enableRobotsTXT = true
googleAnalytics = 'G-Q9P9TKBGSC'
paginate = 5

[outputs]
home = ["HTML", "RSS"]

[params]
contentTypeName = "posts"
themeColor = "green"
authortwitter = "@mpasierbski"
author = "Michal Pasierbski"

[params.twitter]
site = "@mpasierbski"
creator = "@mpasierbski"

[params.utterances]
repo = 'pasierb/pasierb'
issueTerm = 'pathname'
theme = 'preferred-color-scheme'

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = "English"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "archives"
      name = "Archives"
      url = "/archives"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
